# Generated by Django 5.0.4 on 2024-04-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_delete_register_delete_user_categorie_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='url',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='url',
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(upload_to='comments/images/'),
        ),
    ]
