# Generated by Django 5.0.4 on 2024-05-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_alter_product_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='stars',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='stars',
            field=models.FloatField(),
        ),
    ]
