# Generated by Django 5.0.4 on 2024-05-07 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0009_cartitem_delete_cartitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='CartItems',
        ),
    ]
